---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.9
  sha1: 3d6168823f5a8aa6b7427429bc727103e15e27af
- name: bosh-vsphere-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release?v=27
  sha1: 7b9cd2b47138b49cdf9c7329ec6d85324d572743
- name: bosh-ironic-cpi
  url: https://github.com/jriguera/bosh-ironic-cpi-release/releases/download/v1/bosh-ironic-cpi-release-1.tgz
  sha1: 736e2bd4477ffd21836542e50282fa728cca970a

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3262.12
    sha1: 0ec372495a970275495240600e079ee9c173fc22
  cloud_properties:
    cpu: 2
    ram: 4_096
    disk: 20_000
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range: 10.10.0.0/24
    gateway: 10.10.0.1
    dns: [8.8.8.8]
    reserved: [10.10.0.1-10.10.0.200, 10.10.0.210-10.10.0.255]
    cloud_properties:
      name: dvsOnline_XXXXXXX

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: ironic_cpi, release: bosh-ironic-cpi}
  - {name: webdav_metadata_registry, release: bosh-ironic-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.10.0.10]

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    blobstore:
      address: 10.10.0.10
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: ironic-bosh
      db: *db
      cpi_job: ironic_cpi
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    registry:
      host: 10.10.0.10
      port: 25777
      username: registry
      password: registry-pass

    ironic_cpi:
      ironic_url: "http://10.10.10.200:6385/"
      ironic_auth_token: "fake"
      repository_stemcell_url: "http://10.10.10.200/images"
      repository_metadata_url: "http://10.10.10.200/metadata"
      metadata_publickeys:
      - "ssh-rsa AAAAB3Nz ... +vFLV hola@automation"

    agent:
      mbus: "nats://nats:nats-password@10.10.0.10:4222"

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]


vcenter: &vcenter
  address: XX.XX.XX.XX
  user: xxxxxxx
  password: xxxxxxxx
  datacenters:
  - name: Dordrecht
    vm_folder: Online_dev/testBoshVM
    template_folder: Online_dev/boshTemplates
    disk_path: testBoshDisks
    allow_mixed_datastores: false
    datastore_pattern: cf-test-*
    persistent_datastore_pattern: data_cf_test_dogo_01
    clusters:
      - Online_Prod:
          resource_pool: testBosh

cloud_provider:
  template:
    name: vsphere_cpi
    release: bosh-vsphere-cpi
  mbus: "https://mbus:mbus-password@10.10.0.10:6868"
  properties:
    vcenter: *vcenter
    agent:
      mbus: "https://mbus:mbus-password@0.0.0.0:6868"
    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp

